### PR TITLE
Look for the right key for encryptTo

### PR DESCRIPTION
**Pull request by bobobo1618**
To fix https://github.com/someone1/zfsbackup-go/issues/19

### CODE REVIEW

**Comment by someone1** [comment]
Thanks for this! The entire thing needs to be refactored and I have a local branch with a number of fixes - let me get some tests in place here prior to merging to ensure things don't break!

**Comment by ericek111** [comment]
@someone1 Hey, this looks like a great piece of software. Are you still maintaining it? I see that you haven't been really active recently, is everything all right? I'd like to help, but I have zero experience with Go.

**Comment by someone1** [comment]
@ericek111  - Admittedly I have not been able to put in the time I really hope I would be able to for this project. Although I do have a number of unfinished code changes locally - my dev box blew up on my months ago and I haven't recovered everything I was working on since - not to mention a majority of the time I was able to spend on this project was company sponsored and said sponsorship has shifted towards new projects.

It is my sincerest wish/hope to continue maintaining this project and to accept PRs such as this and I hope another push from me will put it on better footing going forward. I just need to dedicate a few days to finish the refactor and get more tests in place.

**Comment by pablofsf** [comment]
@someone1 Have you had any time to work on this task? I have done some preliminary work on [this commit](https://github.com/pablofsf/zfsbackup-go/commit/e6ede761f56b3b11fe15df8c99ab8a2ed32ae27a). It is compiling but still not working. If you believe that it is a good idea to keep working on it, then I can continue the work

**Pull request merged**
